create table if not exists atlas_user
(
    id            bigint generated by default as identity primary key,
    username      varchar(32)  not null,
    email         varchar(128) null,
    password_hash varchar(255) not null,
    created_at    timestamp   not null default current_timestamp,
    updated_at    timestamp   not null default current_timestamp,
    deleted       tinyint     not null default 0
);

create unique index if not exists uk_user_username on atlas_user (username);
create unique index if not exists uk_user_email on atlas_user (email);
create index if not exists idx_user_deleted on atlas_user (deleted);

create table if not exists notebook
(
    id          bigint generated by default as identity primary key,
    user_id     bigint       not null,
    parent_id   bigint       null,
    parent_key  bigint generated always as (coalesce(parent_id, 0)),
    node_type   varchar(16)  not null default 'collection',
    name        varchar(64)  not null,
    description varchar(255) null,
    sort_order  int          not null default 0,
    created_at  timestamp   not null default current_timestamp,
    updated_at  timestamp   not null default current_timestamp,
    deleted     tinyint     not null default 0,
    active_key  bigint generated always as (case when deleted = 0 then 0 else id end)
);

create index if not exists idx_notebook_user on notebook (user_id, deleted, updated_at);

alter table notebook add column if not exists parent_id bigint null;
alter table notebook add column if not exists parent_key bigint generated always as (coalesce(parent_id, 0));
alter table notebook add column if not exists node_type varchar(16) not null default 'collection';
alter table notebook add column if not exists sort_order int not null default 0;
alter table notebook add column if not exists active_key bigint generated always as (case when deleted = 0 then 0 else id end);
update notebook set node_type = 'collection' where node_type is null or node_type = '';
create index if not exists idx_notebook_tree on notebook (user_id, parent_id, deleted, node_type, sort_order, name);
create unique index if not exists uk_notebook_active_sibling on notebook (user_id, parent_key, node_type, name, active_key);

create table if not exists note
(
    id          bigint generated by default as identity primary key,
    user_id     bigint       not null,
    notebook_id bigint       not null,
    title       varchar(128) not null,
    content     clob         not null,
    summary     varchar(512) null,
    search_text clob         null,
    created_at  timestamp   not null default current_timestamp,
    updated_at  timestamp   not null default current_timestamp,
    deleted     tinyint     not null default 0
);

create index if not exists idx_note_user_notebook on note (user_id, notebook_id, deleted, updated_at);

create table if not exists note_history
(
    id           bigint generated by default as identity primary key,
    note_id      bigint       not null,
    user_id      bigint       not null,
    title        varchar(128) null,
    content      clob         null,
    summary      varchar(512) null,
    note_version int          not null,
    created_at   timestamp    not null default current_timestamp
);

create index if not exists idx_note_history_note on note_history (note_id, note_version desc);

create table if not exists tag
(
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null,
    name       varchar(32) not null,
    color      varchar(16) null,
    created_at timestamp   not null default current_timestamp,
    updated_at timestamp   not null default current_timestamp,
    deleted    tinyint    not null default 0
);

create unique index if not exists uk_tag_user_name on tag (user_id, name);
create index if not exists idx_tag_user on tag (user_id, deleted);

create table if not exists note_chunk
(
    id          bigint generated by default as identity primary key,
    user_id     bigint       not null,
    note_id     bigint       not null,
    chunk_index int          not null,
    content     clob         not null,
    embedding   clob         null,
    dim         int          null,
    model       varchar(128) null,
    provider_id bigint       null,
    status      tinyint      not null default 0,
    version     int          not null default 0,
    created_at  timestamp   not null default current_timestamp,
    updated_at  timestamp   not null default current_timestamp
);

create unique index if not exists uk_note_chunk on note_chunk (note_id, chunk_index);
create index if not exists idx_note_chunk_user on note_chunk (user_id, note_id);
create index if not exists idx_note_chunk_status on note_chunk (status);
create index if not exists idx_note_chunk_dim on note_chunk (dim);

create table if not exists paper_attachment
(
    id                bigint generated by default as identity primary key,
    user_id           bigint       not null,
    notebook_id       bigint       not null,
    note_id           bigint       not null,
    original_filename varchar(255) not null,
    stored_filename   varchar(255) not null,
    storage_path      varchar(512) not null,
    content_type      varchar(128) null,
    file_size         bigint       not null,
    extracted_text    clob         null,
    created_at        timestamp    not null default current_timestamp,
    updated_at        timestamp    not null default current_timestamp,
    deleted           tinyint      not null default 0
);

create index if not exists idx_paper_attachment_user on paper_attachment (user_id, deleted, created_at);
create index if not exists idx_paper_attachment_note on paper_attachment (note_id);
alter table paper_attachment add column if not exists extracted_text clob null;

create table if not exists library_item
(
    id                bigint generated by default as identity primary key,
    user_id           bigint       not null,
    notebook_id       bigint       not null,
    note_id           bigint       not null,
    title             varchar(128) not null,
    original_filename varchar(255) not null,
    stored_filename   varchar(255) not null,
    storage_path      varchar(512) not null,
    content_type      varchar(128) null,
    file_ext          varchar(32)  null,
    file_size         bigint       not null,
    category          varchar(64)  null,
    status            varchar(32)  not null,
    extracted_text    clob         null,
    created_at        timestamp    not null default current_timestamp,
    updated_at        timestamp    not null default current_timestamp,
    deleted           tinyint      not null default 0
);

create index if not exists idx_library_item_user on library_item (user_id, deleted, created_at);
create index if not exists idx_library_item_notebook on library_item (notebook_id, deleted, created_at);
create index if not exists idx_library_item_note on library_item (note_id);

create table if not exists ai_provider
(
    id         bigint generated by default as identity primary key,
    name       varchar(64)  not null,
    base_url   varchar(255) not null,
    api_key    varchar(255) null,
    enabled    tinyint      not null default 1,
    remark     varchar(255) null,
    created_at timestamp    not null default current_timestamp,
    updated_at timestamp    not null default current_timestamp
);

create unique index if not exists uk_provider_name on ai_provider (name);

create table if not exists ai_model
(
    id          bigint generated by default as identity primary key,
    provider_id bigint       not null,
    kind        varchar(16)  not null,
    name        varchar(128) not null,
    alias       varchar(64)  null,
    dim         int          null,
    enabled     tinyint      not null default 1,
    remark      varchar(255) null,
    created_at  timestamp   not null default current_timestamp,
    updated_at  timestamp   not null default current_timestamp
);

create unique index if not exists uk_model_provider_name_kind on ai_model (provider_id, name, kind);
create index if not exists idx_model_kind_enabled on ai_model (kind, enabled);

create table if not exists ai_active
(
    id         bigint generated by default as identity primary key,
    scope      varchar(32) not null default 'system',
    kind       varchar(16) not null,
    model_id   bigint     not null,
    updated_at timestamp  not null default current_timestamp
);

create unique index if not exists uk_active_scope_kind on ai_active (scope, kind);

create table if not exists ai_agent
(
    id             bigint generated by default as identity primary key,
    name           varchar(64)   not null,
    model_id       bigint        not null,
    system_prompt  clob          not null,
    vcp_folder     varchar(128)  null,
    enabled        tinyint       not null default 1,
    is_default     tinyint       not null default 0,
    created_at     timestamp     not null default current_timestamp,
    updated_at     timestamp     not null default current_timestamp
);

create index if not exists idx_ai_agent_enabled on ai_agent (enabled, is_default, id);

create table if not exists note_tag
(
    id         bigint generated by default as identity primary key,
    user_id    bigint    not null,
    note_id    bigint    not null,
    tag_id     bigint    not null,
    created_at timestamp not null default current_timestamp
);

create unique index if not exists uk_note_tag on note_tag (note_id, tag_id);
create index if not exists idx_note_tag_user_note on note_tag (user_id, note_id);
create index if not exists idx_note_tag_user_tag on note_tag (user_id, tag_id);

create table if not exists vcp_memory_draft
(
    id                   bigint generated by default as identity primary key,
    user_id              bigint       not null,
    note_id              bigint       not null,
    notebook_id          bigint       not null,
    title                varchar(128) not null,
    memory_content       clob         not null,
    suggested_daily_note varchar(128) null,
    target_daily_note    varchar(128) null,
    status               varchar(24)  not null default 'pending',
    synced_path          varchar(512) null,
    created_at           timestamp    not null default current_timestamp,
    updated_at           timestamp    not null default current_timestamp
);

create index if not exists idx_vcp_draft_user_status on vcp_memory_draft (user_id, status, updated_at);
create index if not exists idx_vcp_draft_note on vcp_memory_draft (note_id);

create table if not exists deepwiki_page
(
    id           bigint generated by default as identity primary key,
    user_id      bigint       not null,
    notebook_id  bigint       not null,
    agent_id     bigint       null,
    mode         varchar(32)  not null,
    focus        varchar(128) null,
    focus_key    varchar(128) not null default '',
    title        varchar(255) not null,
    source_count int          not null default 0,
    markdown     clob         not null,
    created_at   timestamp    not null default current_timestamp,
    updated_at   timestamp    not null default current_timestamp
);

create unique index if not exists uk_deepwiki_page_key on deepwiki_page (user_id, notebook_id, mode, focus_key);
create index if not exists idx_deepwiki_page_notebook on deepwiki_page (user_id, notebook_id, updated_at);

create table if not exists inbox_request
(
    id             bigint generated by default as identity primary key,
    user_id        bigint        not null,
    source_project varchar(128)  not null,
    title          varchar(255)  not null,
    description    varchar(1024) null,
    status         varchar(24)   not null default 'pending',
    imported_count int           not null default 0,
    failed_count   int           not null default 0,
    created_at     timestamp     not null default current_timestamp,
    updated_at     timestamp     not null default current_timestamp
);

create index if not exists idx_inbox_request_user_status on inbox_request (user_id, status, updated_at);

create table if not exists inbox_file
(
    id                bigint generated by default as identity primary key,
    request_id        bigint        not null,
    user_id           bigint        not null,
    original_filename varchar(255)  not null,
    relative_path     varchar(512)  null,
    stored_filename   varchar(255)  not null,
    storage_path      varchar(512)  not null,
    content_type      varchar(128)  null,
    file_size         bigint        not null,
    status            varchar(24)   not null default 'pending',
    note_id           bigint        null,
    library_item_id   bigint        null,
    error_message     varchar(1024) null,
    created_at        timestamp     not null default current_timestamp,
    updated_at        timestamp     not null default current_timestamp
);

create index if not exists idx_inbox_file_request on inbox_file (request_id, status, id);
create index if not exists idx_inbox_file_user on inbox_file (user_id, status, updated_at);
